#Eliminação de gauss (Algoritmo)

A **eliminação de Gauss** (método de eliminação), é um algoritmo utilizado para resolver sistemas lineares. O algoritmo permite transformar um sistema de equações lineares em uma forma escalonada, simplificando a resolução do sistema.

O processo de eliminação de Gauss **consiste em aplicar uma série de operações elementares nas equações do sistema com o objetivo de eliminar uma variável em cada etapa, até que se obtenha um sistema triangular, no qual todas as variáveis são determinadas sequencialmente**. As operações elementares envolvem multiplicar uma equação por um escalar não nulo, somar ou subtrair uma equação por outra, e trocar a posição de duas equações.

O método de eliminação de Gauss é **eficiente para sistemas lineares de pequeno a médio porte**. Ele pode ser implementado manualmente ou utilizando software de computação numérica.

A eliminação de Gauss tem algumas vantagens, como a simplicidade de implementação e a capacidade de resolver sistemas lineares com eficiência. No entanto, também possui algumas limitações, como a sensibilidade a erros de arredondamento em cálculos numéricos e a possibilidade de divisão por zero em determinadas situações.

Em resumo, a eliminação de Gauss é um método amplamente utilizado para resolver sistemas lineares, oferecendo uma abordagem sistemática para simplificar as equações e encontrar a solução. É uma ferramenta fundamental em matemática, física, engenharia e outras áreas que lidam com sistemas de equações lineares.

##Algoritmo de Eliminação de Gauss

In [ ]:
# Função responsável por resolver sistemas lineares quadraticos
# A é a matriz; b é o vetor com os valores a serem igualados
def eliminacao_gauss(A, b):
    n = len(A) # Pega o tamanho da matriz
    
    # Etapa de eliminação
    for indice in range(n):
        if A[indice][indice] == 0:
            raise ValueError("Divisão por zero.")
        
        for j in range(indice+1, n):
            factor = A[j][indice] / A[indice][indice]
            for k in range(indice, n):
                A[j][k] -= factor * A[indice][k]
            b[j] -= factor * b[indice]
    
    # Etapa de retrosubstituição
    x = [0] * n
    x[n-1] = b[n-1] / A[n-1][n-1]
    
    for i in range(n-2, -1, -1):
        soma_valores = 0
        for j in range(i+1, n):
            soma_valores += A[i][j] * x[j]
        x[i] = (b[i] - soma_valores) / A[i][i]
    # Retorna o resultado em uma tupla
    return x

In [ ]:
from numpy import array

A = array([[2,1,-1], 
            [1,-1,2], 
            [3,0,0]], float)
b = array([10,1,6], float)

print(eliminacao_gauss(A, b))

[2.0, 11.0, 5.0]


##Algoritmo Eliminação de Gauss com numpy

In [ ]:
import numpy as np

def eliminacao_gauss_numpy(A, b):
    n = len(A)
    
    # Etapa de eliminação
    for i in range(n):
        if A[i][i] == 0:
            raise ValueError("Divisão por zero. Não é possível aplicar o método de Gauss.")
        
        for j in range(i+1, n):
            factor = A[j][i] / A[i][i]
            A[j] -= factor * A[i]
            b[j] -= factor * b[i]
    
    # Etapa de retrosubstituição
    x = np.zeros(n)
    x[n-1] = b[n-1] / A[n-1][n-1]
    
    for i in range(n-2, -1, -1):
        sum_val = np.dot(A[i, i+1:], x[i+1:])
        x[i] = (b[i] - sum_val) / A[i][i]
    
    return x

In [ ]:
from numpy import array

A = array([[2,1,-1], 
            [1,-1,2], 
            [3,0,0]], float)
b = array([10,1,6], float)

print(eliminacao_gauss_numpy(A, b))

[ 2. 11.  5.]


##Algoritmo de Gauss (scipy)

In [ ]:
from numpy import array
from scipy.linalg import solve, inv 
import random as rd

equacao_1 = [5, 2, rd.randint(0,9), rd.randint(15,30), rd.randint(0,15)]
equacao_2 = [0, 0, rd.randint(0,9), rd.randint(15,30), rd.randint(0,15)]
equacao_3 = [1, 3, rd.randint(0,9), rd.randint(15,30), rd.randint(0,15)]
equacao_4 = [5, 3, rd.randint(-10,100), rd.randint(15,30), rd.randint(0,15)]
equacao_5 = [8, 0, rd.randint(-10,9), rd.randint(4,150), rd.randint(0,15)]

a = array([equacao_1, equacao_2, equacao_3, equacao_4, equacao_5], float)
b = array([rd.randint(0, 10),
           rd.randint(0, 10),
           rd.randint(0, 10), 
           rd.randint(-2, 15),
           rd.randint(5, 25)], float)

x = solve(a, b)
print(x)

[ 0.93030559  0.24514271 -0.10523137  0.09205982  0.55859667]


In [ ]:
from numpy import array
from scipy.linalg import solve, inv 

A = array([[3, 2, 2], 
           [5, 1, 1],
           [3, 5, 2]], float)
b = array([9.865, 3.1415, 5.5], float)

x = solve(A, b)
print(x)

[-0.51171429 -1.455       7.15507143]


##Algoritmo de Jacobi

In [ ]:
import numpy as np

def jacobi(A, b, x0, max_iterations=100, tolerance=1e-6):
    n = len(A)
    x = x0.copy()
    x_new = np.zeros_like(x)
    iterations = 0
    error = np.inf
    
    while error > tolerance and iterations < max_iterations:
        for i in range(n):
            x_new[i] = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
        
        error = np.linalg.norm(x_new - x)
        x = x_new.copy()
        iterations += 1
    
    return x


In [10]:
import numpy as np

def jacobi(A, B, x0, max_iter=100, tol=1e-6):
    n = len(A)
    x = np.copy(x0)
    x_prev = np.copy(x0)
    
    for k in range(max_iter):
        for i in range(n):
            soma = 0
            for j in range(n):
                if j != i:
                    soma += A[i][j] * x_prev[j]            
            x[i] = (B[i] - soma) / A[i][i]
        
        if np.linalg.norm(x - x_prev) < tol:
            break
        
        x_prev = np.copy(x)    
    return x

# Exemplo de sistema linear
A = np.array([[2, 1, -1],[-3, -4, 2],[1, 2, 5]])
B = np.array([8, -5, 9])
x0 = np.array([0, 0, 0])

# Resolvendo o sistema usando o método de Jacobi
x = jacobi(A, B, x0)
print("Solução:", x)

Solução: [ 5 -2  1]


In [ ]:
# Exemplo de sistema linear
A = np.array([[2, 1, -1],
              [-3, -4, 2],
              [1, 2, 5]])
B = np.array([8, -5, 9])
x0 = np.array([0, 0, 0])

# Resolvendo o sistema usando o método de Jacobi
x = jacobi(A, B, x0)

print("Solução:")
print(x)

###Implementação Método Jacobi sem numpy

In [4]:
def jacobi(A, b, x0, max_iterations=100, tolerance=1e-6):
    n = len(A)
    x = x0.copy()
    
    for k in range(max_iterations):
        x_prev = x.copy()
        
        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i][j] * x_prev[j]
            
            x[i] = (b[i] - sigma) / A[i][i]
        
        norm_diff = max(abs(x[i] - x_prev[i]) for i in range(n))
        if norm_diff < tolerance:
            break
    
    return x

# Exemplo de uso
A = [[2, 1, -1],
     [-3, -4, 2],
     [1, 2, 5]]

b = [8, -5, 9]
x0 = [0, 0, 0]

solution = jacobi(A, b, x0)
print("Solução:", solution)


Solução: [6.034481245344585, -2.482757203874656, 1.5862064540355194]


In [9]:
def jacobi(A, b, valor_inicial, max_iter=100, tolerancia=1e-6):
    n = len(A)
    x = valor_inicial.copy()
    x_prev = valor_inicial.copy()
    
    for _ in range(max_iter):
        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i][j] * x_prev[j]
            x[i] = (b[i] - sigma) / A[i][i]
        
        #Verifica se o resultado é aceitavel pelo valor passado na 
        # tolerância
        diferenca = max(abs(x[i] - x_prev[i]) for i in range(n))
        if diferenca < tolerancia:
            break

        x_prev = x.copy()
    return x

# Exemplo de uso
A = [[2, -1, 1],[3, 4, -2],[1, 2, 5]]
b = [9, -5, 3]
valor_inicial = [0, 0, 0]

resultado = jacobi(A, b, valor_inicial)
print("Solução:", resultado)


Solução: [2.6119408730155445, -2.6417907050970193, 1.1343279022263517]
